### ISSUE TITLE
about center loss implement

### ISSUE THREAD

**Issue by valencebond** [zhmiao/OpenLongTailRecognition-OLTR#10]
i am not very sure about center loss implement. Why do we need implement attracting loss using DiscCentroidsLossFunc(torch.autograd.function)?  Can we just implement as repelling loss？

**Comment by zhmiao** [comment]
Hello @valencebond 

First of all, by using the attracting loss, the classification confidence could be higher. At the same time, since we are also trying to use distance as the scoring metric for open class detection. If we force the samples of each class to be more compact to their corresponding centroids, during testing, with the help of reachability, it is more likely that samples of open class can have larger distances to centroids compared to samples of known classes. Does this make sense to you?

**Comment by valencebond** [comment]
hi @zhmiao, thanks for your detailed explanation. Maybe I didn't express my problem clearly. My question is why we need to calculate attract loss gradient by handwriting using **DiscCentroidsLossFunc**  backward functions. Is it essential for DiscCentroidsLossFunc backward function? Can we just compute loss as forward of DiscCentroidsLossFunc without backward function.

**Comment by zhmiao** [comment]
Hello @valencebond Actually there was no good reason why we use this specific implementation. It was possible to simply write a forward function and let pytorch handle the backward. We believe both way should work as fine.

**Comment by valencebond** [comment]
thanks for your replay~

**Comment by xyy19920105** [comment]
hi, I want to ask a question about DiscCentroidsLoss's computation. In DiscCentroidsLoss, there are two loss, loss_attract and loss_repel computed. I think they are the same and  the varieties  of center loss . Why do we need to compute loss twice?
