### ISSUE TITLE
Openset f-measure calculation problem

### ISSUE THREAD

**Issue by Lilyo** [zhmiao/OpenLongTailRecognition-OLTR#37]
Could you please show us how do you determine the "Positive" & "Negative" for F-measure?
think like some other guys also concern about that :)

**Comment by Lilyo** [comment]
hi, @zhmiao , I have checked the [paper](https://arxiv.org/pdf/1511.06233.pdf) you mention, 

Original content:
"For example, when testing the system with images from validation set, fooling set and open set (see Fig. 3), true positives are defined as the correct classifications on the validation set, false positives are incorrect classifications on the validation set and false negatives are images from the fooling set and open set categories that the system incorrectly classified as known examples."

right now I known you follow the same setting from above paper! 
BUT, the original meaning of "false negatives" is mean data from _validation set_, and incorrectly classified to fooling set and open set categories. Why they define  as "images from the _fooling set and open set categories_ that the system incorrectly classified as known examples"?

**Comment by zhmiao** [comment]
Hello @Lilyo , thank you very much for asking. Yes, I agree this metric is a little bit confusing. The reason why the authors treat images from the open set that are incorrectly classified as known samples as false negative is because this whole setting is fundamentally an open set detection problem. We need to identify open set samples at the same time be correct for the closed set classification. When considering both aspects, the authors designed this specific metric. This definitely is not a perfect metric, and we think it is still an open problem that needs improvement from all different directions. Thanks again.

**Comment by Lilyo** [comment]
Yes, @zhmiao , this makes more sense now!
