### ISSUE TITLE
stronger model for imagenet

### ISSUE THREAD

**Issue by twangnh** [zhmiao/OpenLongTailRecognition-OLTR#43]
I'm wondering if you have tried stronger model on imagenet, as resNet10's performance is comparitively low than other larger models like resnet50?

**Comment by zhmiao** [comment]
@twangnh Thanks for asking. The reason why we only use resnet 10 was that our resources are limited. This was also the reason why we freezed the weights of resnet 152. On the other hand, since our method is not about network architecture, as long as the backbones for each baseline are the same we can compare the performance. This paper is mainly about modularized approaches, proof of concept, and benchmark proposition. It is still an open-ended problem, and you are very welcome to further push the performance with deeper, larger networks and all other approaches.

**Comment by liuziwei7** [comment]
Another important reason we use ResNet-10 as the backbone network is that we want to make a fair comparison with the few-shot learning literatures, where ResNet-10 is a typical backbone in the field. Some follow-up works on long-tailed recognition (e.g. https://openreview.net/pdf?id=r1gRTCVFvB) have already experimented with other backbones like ResNet-50 and ResNet-101. You could definitely check them out.
