### ISSUE TITLE
Can you explain the implementation of the disccentroidloss?

### ISSUE THREAD

**Issue by tonysy** [zhmiao/OpenLongTailRecognition-OLTR#47]
Hi, thanks for your work.
I am confusing about the implementation of the disccentroidloss,  could you share the correct mathematical formulation of this loss function. I think the implementation is different from the paper details (equation. 9)

Thanks.

**Comment by zhmiao** [comment]
Hello @tonysy , sorry for the late reply! In Eq(9), basically it is positive the distance to corresponding centroids, and negative the distance to other centroids. The only difference is that we not only calculate the distance to centroids but also calculate dot product to centroids for repelling loss. Because we did normalization to the final feature, dot product is just the cosine similarity, another distance metric. We did not specify this in the paper. We will update the paper accordingly. Thanks again.

**Comment by zhmiao** [comment]
It has been 26 days since last comment. I will close this issue now. If you have any more questions, please reopen this issue. Thanks.
